### ISSUE TITLE
Is there a way to save the original bam files?

### ISSUE THREAD

**Issue by fhsantanna** [TRON-Bioinformatics/covigator-ngs-pipeline#14]
Great tool.
I was wondering if it is possible to save the bams after running the pipeline. I suspect that in my data we have two sars-cov-2 lineages in a sample, and I want to plot a stacked barplot using the count data of the nucleotides per position.
It would be a time saver if I had the bam files.

**Comment by priesgo** [comment]
Thanks @fhsantanna !

There is this flag which should server your purposes `--keep_intermediate`. Let me know if it works.

I just noticed it is undocumented in any case, I will amend that.

**Comment by fhsantanna** [comment]
Thank you very much!

**Comment by priesgo** [comment]
Closing this one, it is documented already.
