### ISSUE TITLE
In which step exactly are homoplasmic mutations taken care of

### ISSUE THREAD

**Issue by Rohit-Satyam** [TRON-Bioinformatics/covigator-ngs-pipeline#26]
HI @priesgo 

I was reading the following posts: [Post 1](https://virological.org/t/issues-with-sars-cov-2-sequencing-data/473) and [Post2](https://virological.org/t/masking-strategies-for-sars-cov-2-alignments/480) that suggest few regions to be masked before alignment step. I can see that in your pipeline there is a vcf file named [problematic_sites](https://github.com/TRON-Bioinformatics/covigator-ngs-pipeline/blob/master/reference/problematic_sites_sarsCov2.vcf.gz) which I think highlights these regions. But I can't figure out in which module you use this file to mask the regions. Can you point me to that module?

Maybe this is a naive question but will it be appropriate to use this `problematic_sites` vcf file to mask regions assembllies generated using Nanopore data as well?

**Comment by priesgo** [comment]
Hi @Rohit-Satyam, thanks for the feedback. We actually considered using that VCF file but only later we did drop it from the pipeline, I cannot recall any particular reason other than time constraints honestly. I will try to integrate this in the next release I am planning to do this week. Will keep you updated.

About the nanopore data... probably... I will discuss this with some colleagues.

**Comment by priesgo** [comment]
Sorry @Rohit-Satyam I actually discussed this time ago and forgot to update here. So, the homoplasic sites from De Maio are actually identified from GISAID assemblies many of which are derived from Nanopore data. We think it would be fine to mask Nanopore VCFs with these sites. 

Talking of which, our VCF of problematic sites is a copy of this one https://github.com/W-L/ProblematicSites_SARS-CoV2. We need to update it, if you are planning to use it I suggest you update it.

Still need to add the option to use that masking VCF in the pipeline...

**Comment by Rohit-Satyam** [comment]
Hi @priesgo. I heard back from GISAID team and they said

>You don’t need to mask homoplasmic sites before submitting sequences to GISAID.

**Comment by priesgo** [comment]
Yes, interesting. Let us know if you find the time and motivation to experiment with that.

**Comment by priesgo** [comment]
This is solved now as per PR above
