### ISSUE TITLE
A special variant case which phasing.py is unable to resolve 

### ISSUE THREAD

**Issue by Rohit-Satyam** [TRON-Bioinformatics/covigator-ngs-pipeline#36]
The script `phasing.py` is unable to resolve these two variants and throws error 

```
    result = parse_gtf(
  /home/subudhak/miniconda3/envs/temp/lib/python3.9/site-packages/gtfparse/read_gtf.py:151: FutureWarning: The error_bad_lines argument has been depr
ecated and will be removed in a future version.


    result = parse_gtf(
  INFO:root:Extracted GTF attributes: ['description=ORF1a', 'description=surface', 'description=ORF3a', 'description=envelope', 'description=membrane
', 'description=ORF6', 'description=ORF7a', 'description=ORF7b', 'description=ORF8', 'description=nucleocapsid', 'description=ORF10']
  WARNING: --discard-invalid-alignments in the future will be activated by default.
  Note: the --sample option not given, applying all records regardless of the genotype
  The fasta sequence does not match the REF allele at MN908947.3:28361:
     REF .vcf: [GGAGAACGCAGAGAACGCA]
     ALT .vcf: [GG]
     REF .fa : [GGAGAACGCAGTGGGGCGC]G


```
```
MN908947.3      28361   .       GGAGAACGCA      G       177.149 PASS    DP=191;DPS=87,104;Pool=1;vafator_af=0.65021;vafator_ac=158;vafator_dp=243;vaf
ator_eaf=0.5;vafator_pu=1;vafator_pw=1;vafator_k=5;vafator_bq=0,0;vafator_mq=60,60;vafator_pos=157,175.5;vafator_rsmq=0.993;vafator_rsmq_pv=0.32086;v
afator_rspos=0.766;vafator_rspos_pv=0.44359   GT:GQ   1:177
MN908947.3      28362   .       GAGAACGCA       G       146.658 PASS    DP=49;DPS=40,9;Pool=2;vafator_af=0.0125;vafator_ac=3;vafator_dp=240;vafator_e
af=0.5;vafator_pu=0;vafator_pw=1;vafator_k=5;vafator_bq=0,0;vafator_mq=60,60;vafator_pos=164,140;vafator_rsmq=-0.481;vafator_rsmq_pv=0.63073;vafator_
rspos=-1.828;vafator_rspos_pv=0.06749 GT:GQ   1:147
```

After running `phasing.py`

```
MN908947.3      28361   .       GGAGAACGCAGAGAACGCA     GG      177.149 PASS    DP=191;DPS=87,104;Pool=1;vafator_af=0.65021;vafator_ac=158;vafator_dp
=243;vafator_eaf=0.5;vafator_pu=1;vafator_pw=1;vafator_k=5;vafator_bq=0,0;vafator_mq=60,60;vafator_pos=157,175.5;vafator_rsmq=0.993;vafator_rsmq_pv=0
.32086;vafator_rspos=0.766;vafator_rspos_pv=0.44359     GT:GQ   1:177
```

**Comment by priesgo** [comment]
Thanks for the feedback as always @Rohit-Satyam 

I was looking into this funny case and made some changes to alleviate this problem in #37. Our intention was to merge only clonal mutations, the rationale is that considering that SARS-CoV-2 is haploid two mutations with high VAF should be in the same molecule (ie: as there is only one, as opposed to for instance diploid organisms). Our arbitrary threshold to consider a mutation clonal is 0.8. In this example above, you can see that both mutations are below this threshold, one in particular has a VAF around 1%. This is most likely a bad indel call, but even if it was a legitimate call these two indels cannot be in phase.

So, I added a couple of conditions to avoid this situation in the future, see #37. But the question remains, where are these mutations coming from? If this come from our pipeline, maybe there is something else we need to fix upstream about the annotation by frequency of mutations.

**Comment by Rohit-Satyam** [comment]
Hi @priesgo Thanks for your prompt reply. No, these VCFs are generated by `wf-artic pipeline`. However, since they only perform Normalisation but do not perform phasing I thought of performing it myself using your `phasing.py` script. You can see that there is a `pool` tag in the INFO section. So it's not an issue with you pipeline as such

**Comment by priesgo** [comment]
OK, interesting! I am happy to see that we facilitate innovation :)

I suggest that you replicate what we do. We actually fix a threshold for clonal mutations (eg: we use 0.8) and then everything below that has a FILTER value different than PASS. Then the actual `phasing.py` will only phase the PASS mutations.

To perform that filtering we use `bcftools filter`, see here https://github.com/TRON-Bioinformatics/covigator-ngs-pipeline/blob/master/modules/06_variant_annotation.nf#L71

I will close this for now, feel free to reopen.

**Comment by priesgo** [comment]
I just added the support for input of VCF files in #38 . That basically takes your VCF and optionally BAM file and runs it through the same pipeline we run for VCFs. That should allow you to process your VCF files with an equivalent pipeline.
