### ISSUE TITLE
ONT sequencing data

### ISSUE THREAD

**Issue by smanfri** [TRON-Bioinformatics/covigator-ngs-pipeline#45]
In the section "Future work" of the README file it's stated that you would like to add a feature for analyse also ONT sequencing data. I would like to know if you are working on this and if you have some idea of when this feature is going to be available.
Many thanks, 
Sara

**Comment by priesgo** [comment]
Apologies for the ultra-late reply, I have been lately dragged away from work.

We have already done some efforts in this line, we have a working prototype that we now need to integrate with the rest of the pipeline. It is not the highest priority but it is planned to happen in the following months. Thanks for your patience!

**Comment by priesgo** [comment]
FYI @patricksorn @johausmann

**Comment by priesgo** [comment]
We have an open PR on this. I am closing this request on behalf of that. We will hopefully have this sooni-ish ready.

Feel free to reopen.
